syntax = "proto3";
package Fantasy.Network.Message;
// 协议分为:
// ProtoBuf:可以在Outer和Inner文件里使用。
// MemoryPack:可以在Outer和Inner文件里使用。
// Bson:仅支持在Inner文件里使用。
// 使用方式:
// 在message协议上方添加// Protocol+空格+协议名字
// 例如:// Protocol ProtoBuf 或 // Protocol MemoryPack

//注册账号请求
message RegisterAccountRequest // IRequest, RegisterAccountResponse
{
  string account = 1;
  string pass = 2;
}

message RegisterAccountResponse // IResponse
{
  string account = 1;
  string pass = 2;
}

//注册姓名请求
message RegisterNameRequest // IRequest , RegisterNameResponse
{
  string accountName = 1;
  string name = 2;
}

message RegisterNameResponse // IResponse
{
  string accountName = 1;
  string name = 2;
}

message EntryLobbyRequest // IRequest , EntryLobbyResponse
{
  int64 accountId = 1;
}

message EntryLobbyResponse // IResponse
{
  StateSyncData selfData = 1;
  repeated StateSyncData otherPlayerData = 2;
}







///玩家登录请求
message LoginRequest // IRequest , LoginResponse
{
  string account = 1;
  string pass = 2;
}
message LoginResponse // IResponse
{
  int64 accountId = 1;
  string accountName = 2;
}
//其他玩家登录广播
message OtherPlayerLoginMessage // IMessage
{
  StateSyncData playerData = 1;
}

//玩家主动退出消息
message LogoutMessage // IMessage
{
  int64 playerId = 1;
}

//当其他玩家退出时广播
message OtherPlayerLogoutMessage // IMessage
{
  int64 playerId = 1;
}

//状态同步请求
message StateSyncRequest // IRequest , StateSyncResponse
{
  int64 tatePackageId = 1;
  StateSyncData stateData = 2;
}

message StateSyncResponse // IResponse
{
  int64 statePackageId = 1;
  StateSyncData stateData = 2;
}

//广播玩家状态数据
message OtherPlayerStateSyncMessage // IMessage
{
  StateSyncData roleData = 1;
}



//组队相关
message CreateTeamRequest // IRequest , CreateTeamResponse
{
  int64 playerId = 1;
}

message CreateTeamResponse // IResponse
{
  int64 teamId = 1;
  int64 playerId = 2;
}

message JoinTeamRequest // IRequest , JoinTeamResponse
{
  int64 teamId = 1;
  int64 playerId = 2;
}

message JoinTeamResponse // IResponse
{
  int64 teamId = 1;
  int64 teamOwnerId = 2;
  repeated int64 teamMemberIds = 3;
}

message TeamStateChangeMessage // IMessage
{
  int32 teamState = 1; //1 : 玩家加入 / 2 : 玩家离开 / 3 : 队伍解散
  int64 playerId = 2;
}




//进入副本相关
message EnterDungeonMessage // IMessage
{
  int64 teamId = 1;
  repeated int64 teamMemberIds = 2;
}

message LoadDungeonProgressMessage // IMessage
{
  int64 teamId = 1;
  int64 playerId = 2;
  float progress = 3;
}

message StartDungeonBattleMessage // IMessage
{
  repeated BattlePlayerData battlePlayers = 1;
}

// 同步玩家状态数据
message StateSyncData
{
  int64 playerId = 1;
  CSVector3 position = 2;
  CSVector3 inputDir = 3;
  int32 playerState = 4;
  string PlayerName = 5;
}

//三维向量 , 传输位置使用
message CSVector3
{
  float x = 1;
  float y = 2;
  float z = 3;
}




//操作帧数据 要保证传输越小越好，越小传输越快
message FrameOperationData
{
  int32 operateType = 1;  //0 : 无操作 , 1 : 移动 , 2 : 技能
  CSFixIntVector3 inputDir = 2;
  int32 skillId = 3;
  int32 skillType = 4;  //1:普通技能 2:引导技能 3:蓄力技能
  CSFixIntVector3 skillPos = 5; //引导技能位置
  int64 playerId = 6;
}

message FrameOperateEventMessage_C2G // IMessage
{
  int64 battleId = 1;
  repeated FrameOperationData frameOperateDataList = 2;
}

message FrameOperateEventMessage_G2C // IMessage
{
  int64 battleId = 1;
  repeated FrameOperationData frameOperateDataList = 2;
  int64 logicFrameId = 3; //当前逻辑帧ID
}



//双端通用定点数
message CSFixIntVector3
{
  int32 x = 1;
  int32 y = 2;
  int32 z = 3;
}

message BattlePlayerData
{
  int64 playerId = 1;
  string playerName = 2;
}







